wish: wish.c common.h common.c command.h command.c path.h path.c parse.h parse.c exec.h exec.c
	gcc -g -Wall -Werror -o wish wish.c common.c command.c path.c parse.c exec.c

.PHONY: clean
clean:
	rm wish